import {
  Wifi,
  Flame,
  Car,
  Wind,
  PawPrint,
  Users,
  Bed,
  Bath,
  Tv,
  WashingMachine,
  ChevronDown,
  ChevronUp,
  Home,
  Mountain,
  Heart,
  UtensilsCrossed,
  MapPin,
  Calendar,
  Star,
  Trees,
  Menu, 
  PlugZap,
  X,
  Droplet,
  Phone,
  Mail,
  MapPinHouse,
  Waves,
  Fish,
  Bird,
  Dumbbell,
  Hamburger,
  DoorOpen,
  Trash
} from "lucide-react";
import {
  FaFacebookF,
  FaInstagram,
} from "react-icons/fa";
import { RiBilliardsFill } from "react-icons/ri";

export const iconMap = {
  fish:Fish,
  waves:Waves,
  wifi: Wifi,
  "fire-pit": Flame,
  "free-parking": Car,
  "air-conditioning": Wind,
  "pet-friendly": PawPrint,
  guests: Users,
  bed: Bed,
  bath: Bath,
  tv: Tv,
  phone:Phone,
  mail:Mail,
  "map-pin-house":MapPinHouse,
  "washing-machine": WashingMachine,
  "chevron-down": ChevronDown,
   "chevron-up": ChevronUp,
  home: Home,
  mountain: Mountain,
  heart: Heart,
  kitchen: UtensilsCrossed,
  "map-pin": MapPin,
  calendar: Calendar,
  star: Star,
  trees: Trees,
  menu: Menu,
  x: X,
  "plug-zap": PlugZap,
  trash: Trash,
  droplet:Droplet,
  bird:Bird,
  dumbbell:Dumbbell,
  hamburger:Hamburger,
  "door-open": DoorOpen,
  facebook: FaFacebookF,
  instagram: FaInstagram,
  "pool-table": RiBilliardsFill
};

export type IconName = keyof typeof iconMap;