import {
  Wifi,
  Flame,
  Car,
  Wind,
  PawPrint,
  Users,
  Bed,
  Bath,
  Tv,
  WashingMachine,
  ChevronDown,
  Home,
  Mountain,
  Heart,
  UtensilsCrossed,
  MapPin,
  Calendar,
  Star,
  Trees,
  Menu, 
  X,
  Droplet,
  Phone,
  Mail,
  MapPinHouse,
  Waves,
Fish,
} from "lucide-react";
import {
  FaFacebookF,
  FaInstagram,
} from "react-icons/fa";

export const iconMap = {
  fish:Fish,
  waves:Waves,
  wifi: Wifi,
  "fire-pit": Flame,
  "free-parking": Car,
  "air-conditioning": Wind,
  "pet-friendly": PawPrint,
  guests: Users,
  bed: Bed,
  bath: Bath,
  tv: Tv,
  phone:Phone,
  mail:Mail,
  "map-pin-house":MapPinHouse,
  "washing-machine": WashingMachine,
  "chevron-down": ChevronDown,
  home: Home,
  mountain: Mountain,
  heart: Heart,
  kitchen: UtensilsCrossed,
  "map-pin": MapPin,
  calendar: Calendar,
  star: Star,
  trees: Trees,
  menu: Menu,
  x: X,
  "droplet":Droplet,
  facebook: FaFacebookF,
  instagram: FaInstagram
};

export type IconName = keyof typeof iconMap;